CMakeLists.txt, build.bat, src/test/cs/Infinispan/HotRod/CompatibilityModeTestSuite.cs, src/test/cs/Infinispan/HotRod/JBasicMarshaller.cs, src/test/cs/Infinispan/HotRod/RemoteTaskExecTest.cs, src/test/cs/Infinispan/HotRod/Util/ScriptUtils.cs, src/test/resources/macbeth.txt, src/test/resources/wordCountStream.js
Additional test for remote execution of distributed streams. It includes macbeth.txt which is used by the map/reduce job. This file is a little longer:)
=> Tests for remote script execution

swig/hotrodcs.i
Added header files for events in hotrodcs.i swig file
=> HRCPP-318 # fix hotrodcs.i to build with c++ events

.gitattributes
Added .gitattributes file to enforce LF line endings
=> HRCPP-310 # gitattributes to have only LF

src/main/cs/Infinispan/HotRod/Config/AbstractConfigurationChildBuilder.cs, src/main/cs/Infinispan/HotRod/Config/ClusterConfigurationBuilder.cs, src/main/cs/Infinispan/HotRod/Config/ConfigurationBuilder.cs, src/main/cs/Infinispan/HotRod/Config/ConfigurationChildBuilder.cs
https://jira.jboss.org/browse/HRCPP-328
=> HRCPP-328 Make ClusterConfigurationBuilder chainable

src/test/cs/Infinispan/HotRod/RemoteFulltextQueryTest.cs, src/test/cs/Infinispan/HotRod/RemoteQueryTest.cs, src/test/cs/Infinispan/HotRod/RemoteQueryTestSuite.cs, src/test/cs/Infinispan/HotRod/RemoteQueryUtils.cs, src/test/resources/clustered-indexing.xml, src/test/resources/proto2/bank.proto, src/test/resources/proto3/bank.proto
The TestFullTextTermRightOperandAnalyzed test is failing for me and I have no idea why:-/ The rest is passing.
=> Tests for fulltext queries

src/main/cs/Infinispan/HotRod/Event/ClientEvent.cs, src/main/cs/Infinispan/HotRod/Event/ClientListener.cs, src/main/cs/Infinispan/HotRod/IRemoteCache.cs, src/main/cs/Infinispan/HotRod/Impl/RemoteCacheSWIGImpl.cs, src/test/cs/Infinispan/HotRod/RemoteEventTest.cs
https://issues.jboss.org/browse/HRCPP-335
=> HRCPP-335 API method for remote events start with lower case

src/main/cs/Infinispan/HotRod/Config/AbstractConfigurationChildBuilder.cs, src/main/cs/Infinispan/HotRod/Config/ConfigurationChildBuilder.cs, src/test/cs/Infinispan/HotRod/NearCacheTest.cs
https://issues.jboss.org/browse/HRCPP-336
=> HRCPP-336 NearCacheConfigurationBuilder not fully chainable

src/test/cs/Infinispan/HotRod/Util/PlatformUtils.cs
Provide a robust server shutdown for test suite.
fixes: https://issues.jboss.org/browse/HRCPP-350
=> HRCPP-350 # robust server shutdown for tests

src/test/cs/Infinispan/HotRod/DefaultTestSuite.cs, src/test/cs/Infinispan/HotRod/NearCacheEvictionTest.cs, src/test/cs/Infinispan/HotRod/NearCacheMultipleClientsTest.cs, src/test/cs/Infinispan/HotRod/NearCacheStaleReadsTest.cs
* tests for stale reads
* tests with multiple clients
=> Extend Near Cache test suite

src/main/cs/Infinispan/HotRod/Impl/RemoteCacheSWIGImpl.cs
Correct marshalling for the filter parameters.
Fix for:
https://issues.jboss.org/browse/HRCPP-366
=> HRCPP-366 # Filter args correctly marshalled

src/test/cs/Infinispan/HotRod/RemoteQueryTest.cs, src/test/resources/proto2/bank.proto, src/test/resources/proto3/bank.proto
proto2 required fields need default value to work with proto3 C# client.
Fixes: https://issues.jboss.org/browse/HRCPP-356
=> HRCPP-356 Added defaults for proto required field

src/test/cs/Infinispan/HotRod/RemoteQueryTest.cs
https://issues.jboss.org/browse/HRCPP-410
=> HRCPP-410 Tests for order by

src/test/cs/Infinispan/HotRod/AsyncOperationsTest.cs
https://issues.jboss.org/browse/HRCPP-411
This is just an additional native test for one operation, including exception handling when the cache manager is not started. The feature has otherwise a good test coverage through the Java test suite.
=> HRCPP-411 Async API native tests

src/main/cs/Infinispan/HotRod/IRemoteCache.cs, src/main/cs/Infinispan/HotRod/Impl/JBasicMarshaller.cs, src/main/cs/Infinispan/HotRod/Impl/RemoteCacheSWIGImpl.cs, src/main/cs/Infinispan/HotRod/RemoteCacheManager.cs, src/test/cs/Infinispan/HotRod/AsyncOperationsTest.cs, src/test/cs/Infinispan/HotRod/BaseAuthorizationTest.cs, src/test/cs/Infinispan/HotRod/RemoteTaskExecTest.cs, swig/hotrod_arch.i, swig/hotrodcs.i
usability improved as described in:
https://issues.jboss.org/browse/HRCPP-412
=> HRCPP-412 internalized marshalled for remote exec args

src/test/cs/Infinispan/HotRod/AuthenticationTestSuite.cs, src/test/cs/Infinispan/HotRod/XSiteTestSuite.cs
https://issues.jboss.org/browse/HRCPP-447
=> HRCPP-447 Separate data directories for different server instances

src/Infinispan.HotRod/IRemoteCache.cs, src/Infinispan.HotRod/RemoteCacheManager.cs, src/Infinispan.HotRod/SWIG/RemoteCacheManager.cs, swig/hotrod_arch.i, swig/hotrodcs.i, test/Infinispan.HotRod.Tests/RemoteCacheAdminTest.cs
https://issues.jboss.org/browse/HRCPP-478
=> HRCPP-478 added RemoteCacheManager.GetCacheNames()

examples/ReproducerForHRCPP485/App.config, examples/ReproducerForHRCPP485/Program.cs, examples/ReproducerForHRCPP485/Properties/AssemblyInfo.cs, examples/ReproducerForHRCPP485/ReproducerForHRCPP485.csproj, examples/ReproducerForHRCPP485/ReproducerForHRCPP485.sln
A reproducer application for:
https://issues.jboss.org/browse/HRCPP-485
=> HRCPP-485 C# reproducer example

swig/CMakeLists.txt, swig/hotrodcs.i
This fixes a memory leak between C++ and C# layers
=> HRCPP-491 fixed mem leak

Jenkinsfile, src/Infinispan.HotRod/Exceptions/NoSuchElementException.cs, swig/hotrod_exception.i
NoSuchElementException propagated to the c# layer
=> HRCPP-499 NoSuchElementException exposed

src/Infinispan.HotRod/Infinispan.HotRod.csproj
=> Update to NLog ver. 4.5.11

src/Infinispan.HotRod/Event/ContinuousQueryListener.cs, src/resources/proto/base_types.proto, test/Infinispan.HotRod.Tests/BasicTypesProtostreamMarshaller.cs, test/Infinispan.HotRod.Tests/ContinuousQueryTest.cs
=> Fix namespace problem with proto file.
